# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = '''
$directory$character
'''

right_format = '''
$all
'''

[time]
disabled = false
time_format = '%a %b %d %T'
format = '([\[$time\]]($style))'
style = 'bold yellow'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[cmd_duration]
format = '\[[$duration]($style)\]'

[git_branch]
symbol = " "
format = '([\[$symbol$branch\]]($style))'

[git_commit]
tag_symbol = ""

[git_status]
disabled = false
ahead = '⇡${count}'
behind = '⇣${count}'
deleted = '✘'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '([\[$all_status$ahead_behind\]]($style))'
ignore_submodules = false
modified = '!'
renamed = '»'
staged = '[++\($count\)](green)'
stashed = '\$'
style = 'bold red'
typechanged = ""
untracked = '?'
up_to_date = '✓'

[c]
symbol = "C "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
symbol = "cmake "
format = '\[[$symbol($version)]($style)\]'

[directory]
read_only = " ro"
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false

[docker_context]
symbol = "docker "

[lua]
symbol = "lua "
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
disabled = false
symbol = ""
format = '\[$symbol[$ram( | $swap)]($style)\]'

[rust]
symbol = "rs "
format = '\[[$symbol($version)]($style)\]'

[package]
symbol = "pkg "
format = '\[[$symbol$version]($style)\]'

[python]
symbol = "py "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
