# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt autocd notify
unsetopt beep
bindkey -e

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Include completion
fpath=(~/.zsh/completion $fpath)

# The following lines were added by compinstall
zstyle :compinstall filename '/home/ivan/.zshrc'
autoload -Uz compinit
compinit

# case insensitive path-completion 
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#eval "$(starship init zsh)"
eval "$(oh-my-posh init zsh --config ~/dotfiles/sh/stelbent.minimal.omp.json)"

source ~/.aliases
