#!/bin/bash

tmux new-session -d 'ssh mtp300y' \; \
         split-window -d 'ssh mtp300y' \; \
         split-window -d 'ssh mtp300y' \; \
         split-window -d 'ssh mtp300y' \; \
         select-layout tiled \; \
         attach \; \

